#!/bin/bash

VOLUME_NAME="${@:$#}"
VOLUME_NAME=${VOLUME_NAME#/Volumes/}

/opt/local/bin/ntfs-3g -o volname="${VOLUME_NAME}" -o local -o noappledouble -o negative_vncache -o auto_xattr -o auto_cache -o noatime -o windows_names -o user_xattr -o inherit -o uid=501 -o gid=20 -o allow_other "$@" &> /var/log/ntfsmnt.log

exit $?
